### PR TITLE
Widen `ember-modifier` versions to support v4

### LINKED ISSUE #25: Update to `ember-modifier` v4
`ember-modifier` v4 is [out](https://github.com/ember-modifier/ember-modifier/releases/tag/v4.0.0). It would be nice to update `ember-on-resize-modifier` to use/support it.

### PR DESCRIPTION
**Pull request by boris-petrov**
And add `ember-auto-import` v2 dependency

Sorry I'm not using the PR template.

fixes #25

cc @jherdman

This must be released as a major version as it's a breaking change! See [here](https://github.com/jelhan/ember-style-modifier/blob/1ef844ed23c8ee11eb163bf165f9c1c6d8bc8905/CHANGELOG.md) as an example.

### CODE REVIEW

**Comment by boris-petrov** [comment]
@jherdman - do you mind taking a look at this? I can't update to `ember-modifier` because of that. :)

**Comment by jherdman** [comment]
Unfortunately I know longer participate in the Ember community nor this repo. Perhaps someone at PN can help? Maybe @voltidev ?

**Comment by Benkooo** [comment]
Hello, any updates on this topic? We need to update `ember-modifier` v4 as well:)

**Comment by christophermlne** [comment]
> @ghedamat pinging you because your in the PrecisionNutrion org and mention ember in your profile smile do you think this is likely to get merged, thinking of switching to https://github.com/elwayman02/ember-resize-modifier but switched to this lib last year from https://github.com/gmurphey/ember-did-resize-modifier and don't want to change again 🤞🏻

@mrloop, thank you for this!

**Comment by boris-petrov** [comment]
@christophermlne thanks for the merge! I see there is a "Release 2.0.0" commit in `main` however there is no such version in `npm`. Was there an issue with the release?

**Comment by christophermlne** [comment]
@boris-petrov I'm currently trying to figure out how to publish to npm given the novel monorepo structure of this project

**Comment by Benkooo** [comment]
Hello, following up on this thread. Do you think we could do a release of the package soon ?

**Comment by christophermlne** [comment]
@Benkooo @boris-petrov @mrloop I was finally able to get this published to npm.

We had issues with npm permissions that took some time to diagnose and resolve.

Please find it here: https://www.npmjs.com/package/ember-on-resize-modifier/v/2.0.2

**Comment by mrloop** [comment]
Thanks @christophermlne and thanks @boris-petrov! 🎉

**Pull request merged**
